### ISSUE TITLE
Research Docker integration

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/foodies#12]
Look at how we can integrate Docker into our project. We're hoping to get this implemented so that we can make local development easier for ourselves.

Rob actually did a presentation a while back on Docker so you could also take a look at these for reference: https://slides.ubclaunchpad.com/workshops/guide-to-docker.pdf

Please document any of your findings in this issue so we can all learn more about Docker too!

And last note, @yunishimura0716 if you could figure out how to get Postgres running in a container that would be great.

**Comment by yunishimura0716** [comment]
I created docker environment for #10. I used docker and docker-compose to hold more than a container. I made it by referring some documents but not sure it is good for our product. So, could you review it then give a comment?
[https://dev.to/rubiin/docker-pipeline-with-typescript-express-for-production-20kc](url)
