### ISSUE TITLE
Look into Google Maps API integration

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/foodies#13]
Research the limitations of the Google Maps API, and create a small service (this could just be functions for now) on the back-end that can connect to the API endpoints. Some things that we'd like to be able to do include:
- Being able to embed a map on our site
- How we can programmatically control a map
- How pinning locations works

I'm thinking that it would be best to have these API calls stored on the back-end but it's possible that the front-end might be a better place for it. Please report your findings here!

Upon a quick Google search, I think these two links might be a good place to start:
- https://developers.google.com/maps/documentation/javascript/overview
- https://developers.google.com/maps/documentation/embed/get-started

**Comment by richardyjtian** [comment]
Is there an account that launchpad has for Google APIs? https://developers.google.com/maps/gmp-get-started
