### ISSUE TITLE
Look into Google Places (or Yelp) API integration

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/foodies#14]
Look into the limitations of the Google Places API and create a small service (a set of functions) on the back-end that connect  to the API endpoints. Some examples of data that I think we could use include:
- Restaurant details (name, address, phone number, hours)
- Restaurant reviews (number of reviews, average rating)

Also, I just suggested Google Places API because we'll be using their Maps API but if you think a different API is better suited for the task (like Yelp) feel free to bring that up and we can discuss!

You could probably start by taking a look at these pages:
- https://developers.google.com/places/web-service/overview
- https://www.yelp.ca/fusion

**Comment by ld357** [comment]
Brainstorming doc:
https://docs.google.com/document/d/1VB1m5T601XZMaO-l-brTVzfyISdjWBng9krJK-UmBUw/edit?usp=sharing
