### ISSUE TITLE
Look into embedding Map component

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/foodies#15]
Figure out how to embed a map onto our site. It would probably be a good idea to sync up with Richard since he's working on the Google Maps integration for #13.

**Comment by na-wu** [comment]
Did a bit of research on the libraries we could use for embedding Google Maps. It seems like @richardyjtian has already gone ahead with one of them so I'll leave the other as an option incase we want to pivot.

https://docs.google.com/document/d/1luK83wMa_DmysiIpzjv1OrjiZhLtJdFaJyT7H3fybao/edit?usp=sharing
