### ISSUE TITLE
Create customizable button and dropdown components

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/foodies#16]
We'd need basic button components regardless of the features that will be included in the project. These components would be used to facilitate the filtering and sorting options available to the user on the home page.

We don't have to worry too much about how it looks and the colours; we can just focus on functionality and adjust these UI elements to conform to the high-fi designs later on. I'm thinking that you could look into pre-made components like those offered by [Ant Design](https://ant.design/) or [Material UI](https://material-ui.com/) to speed up development time, but I'd be cautious about the customizability of these elements. If you could look into the limitations of those that would be great!

**Comment by na-wu** [comment]
+1 on Ant Design over MUI
