### ISSUE TITLE
Add sample data for users

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/foodies#35]
## Task 🔨
Create sample data according to the schema for the `User` table and the `Promotion` table. We can also add example queries for these tables so we have an idea of the queries we'll write in the controllers. I think @ericrkuo is also planning to get [`sequelize`](https://sequelize.org/) set up so that we don't have to deal with query strings, so maybe take a look at how you could make these queries using that library.

You can also create sample data for the other tables in the schema (`User_Uploads_Promotion`, `User_Saved_Promotion`, `Promotion_Has_Category`, `Promotion_Category`, `Promotion_Has_Discount`, `Discount`, and `CuisineType`) if you have time.

Database schema: https://docs.google.com/document/d/131JfzQXb472CyOL2yMSqbfuDyGI13UwQgnh0kowzPuk/edit

**Comment by yunishimura0716** [comment]
I firstly made sample data for Users, restaurant, discount and promotion. I'll make by other data through the discussion with @ericrkuo
