### ISSUE TITLE
Add controller for GET /promotion route

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/foodies#36]
The request body could include (TBD, but here are some thoughts):
- user_id (for now, but once we implement usage of JWT I'd prefer to use that in the Authorization header - more info [here](https://en.wikipedia.org/wiki/JSON_Web_Token#Use))

This controller should be able to:
- get the list of all promotions for the given user
- handle query params to filter out response according to given fields: `category`, `cuisine type`, `
- handle `sort_by` query param to sort result by given field: `rating`, `expiry`, `distance`, `popularity`

**Comment by ericrkuo** [comment]
Wait what's the difference between issues 36 and 37?

**Comment by ericrkuo** [comment]
I'll be working on this issue along with https://github.com/ubclaunchpad/foodies/issues/48 at the same time since they're pretty connected.
