### ISSUE TITLE
Add controller for GET /promotion

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/foodies#37]
## Task 🔨

The request body could include (TBD, but here are some thoughts):
- user_id (for now, but once we implement usage of JWT I'd prefer to use that in the Authorization header - more info [here](https://en.wikipedia.org/wiki/JSON_Web_Token#Use))

This controller should be able to:
- get the list of all promotions for the given user
- handle query params to filter out response according to given fields: `category`, `cuisine type`, `
- handle `sort_by` query param to sort result by given field: `rating`, `expiry`, `distance`, `popularity`

The route should respond with:
- status code `200` with all promotions in the response body
- status code `404` if no promotions are found

**Comment by ericrkuo** [comment]
Would it be easier to do the sorting in the front end?
