### ISSUE TITLE
Add controller for POST /promotion

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/foodies#38]
## Task 🔨

The request body could include:
- user_id (refer to note in #37)
- all fields for a valid promotion, according to schema

This controller should be able to:
- add a new entry to the `Promotion` table
- add a new entry to the `Promotion_Has_Category` table, and optionally the `Category` table if it doesn't exist
- add a new entry to the `Promotion_Has_Discount` table, and optionally the `Discount` table if it doesn't exist

The route should respond with:
- status code `201` or `204` if successfully added
- status code `422` if we're unable to process the request

**Comment by ericrkuo** [comment]
I'll be working on this issue along with https://github.com/ubclaunchpad/foodies/issues/48 at the same time since they're pretty connected.
