### ISSUE TITLE
Add controller for POST /promotion/:promotion_id

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/foodies#39]
## Task 🔨

This controller should be able to:
- retrieve the promotion from the Promotion table (joining any other tables if necessary) given the `promotion_id` parameter in the URI

The route should respond with:
- status code 200 if successfully found
- status code 404 if not found

**Comment by ericrkuo** [comment]
I'll be working on this issue along with https://github.com/ubclaunchpad/foodies/issues/48 at the same time since they're pretty connected.
