### ISSUE TITLE
Set up PostgreSQL connection

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/foodies#4]
Task: Get a PostgreSQL pool connection set up.

We just want to get the initial set-up out of the way because this can be a bit time-consuming. We can probably use a module to interface with the database, like [`pg`](https://node-postgres.com/) but feel free to suggest alternatives if you find any.

This is probably blocked by #3 right now, so you could probably just do this in a separate folder for now before integrating it with the back-end boilerplate.

**Comment by yunishimura0716** [comment]
I created sample express Todo app using local postgres. It does not need to merge but can be sample when app connect to postgres database.

**Comment by andrewzulaybar** [comment]
@yunishimura0716 Do you think you could integrate your work into the app this week once #10 gets merged in? Thanks!

**Comment by yunishimura0716** [comment]
I could make the connection between two docker containers (backend and db). So, I will do PR after the docker branch is merged!
