### ISSUE TITLE
Yarn lock

### ISSUE THREAD

**Issue by ericrkuo** [ubclaunchpad/foodies#45]
`yarn.lock` file is now using npm in master branch. Is this a problem, or is it easy to generate a new yarn lock file?
https://github.com/ubclaunchpad/foodies/blob/master/backend/yarn.lock
vs
https://github.com/ubclaunchpad/foodies/blob/backend-setup/backend/yarn.lock

this is in master
![image](https://user-images.githubusercontent.com/49849754/98330258-da2bb480-1fae-11eb-903d-1dd31af76bd2.png)

this is in another branch
![image](https://user-images.githubusercontent.com/49849754/98330275-e31c8600-1fae-11eb-8539-e96e0ad19441.png)

**Comment by ericrkuo** [comment]
Oops didnt mean to assign you, just meant to tag you to ask about this

**Comment by andrewzulaybar** [comment]
@ericrkuo Thanks for bringing it up, it was a quick fix so I thought I'd push it. Check out #46
