### ISSUE TITLE
Spike: research how we are going to implement upvote/downvote functionality

### ISSUE THREAD

**Issue by ericrkuo** [ubclaunchpad/foodies#49]
Edit** Most likely not needed for MVP yet, depending on time.

This will require some database changes in the BE and also need to talk with design team how we are going to design this feature.

Maybe frontend can detect whether user is spamming it, and once the user has left the button for X amount of seconds, then we send a request to BE to update the votes.

Research:
- TypeORM has repository increment/decrement functionality

**Comment by na-wu** [comment]
Since we're using express, we could set up a rate limiter as middleware to reduce any sort of backend overload. I wrote a similar one here that could probably be modified for our use case

https://github.com/na-wu/qrapi/blob/master/ratelimiter.js

**Comment by ericrkuo** [comment]
Totally agree, I was thinking along the same lines, that would be great. But how about cases if a user likes 5 separate promotions very fast. Do we want to batch these operations altogether and make it one transaction to save all 5 promotions at once?

**Comment by na-wu** [comment]
I think handling 5 operations in a rapid manner should be pretty harmless, the way I imagine it is a user shouldn't notice any rate limiting under normal use cases, nor should we prevent users from saving multiple promotions in a short period of time. The number of operations allowed per second can probably be adjusted to what we might consider "normal".

**Comment by ericrkuo** [comment]
That makes sense yah
