### ISSUE TITLE
Start lo-fi wireframes 

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/foodies#6]
Task: start low fidelity wireframes and iterate using feedback from user surveys, interviews, and devs.

Feel free to add more information to this ticket about progress and/or updates.

**Comment by wendoz** [comment]
[Flowchart.pdf](https://github.com/ubclaunchpad/foodies/files/5418378/Flowchart.pdf)

**Comment by wendoz** [comment]
[Flowchart.pdf](https://github.com/ubclaunchpad/foodies/files/5418382/Flowchart.pdf)

**Comment by andrewzulaybar** [comment]
Closing this ticket because we're planning to just keep our design tasks on the Kanban board and not in Github issues.
