### ISSUE TITLE
Implement Place Details - ID Refresh SKU Periodically 

### ISSUE THREAD

**Issue by ld357** [ubclaunchpad/foodies#70]
Although we're able to store place_id's indefinitely for our restaurants, it's a good idea to refresh them periodically because we may occasionally hit a NOT_FOUND status code. This is because businesses close, or move to a new location, etc.

To do, make a new Place Details - ID Refresh SKU request with only the ID field in the parameter. 

[More Information Here](https://developers.google.com/places/web-service/place-id#save-id) 

Need to look into what this exactly means as well -> "One strategy is to store the original request that returned each place ID. If a place ID becomes invalid, you can re-issue that request to get fresh results. These results may or may not include the original place. The request is chargeable."

**Comment by ld357** [comment]
@ericrkuo I still need to look into what "storing original request" means, but if this just means sending a Place Search request again, we might need to store the name and location submitted by the user in the database!

**Comment by ericrkuo** [comment]
Hmm sorry not sure what you mean, is there something in the doc we wrote about that doesn't make sense?

**Comment by ericrkuo** [comment]
I am not sure if we can refresh routinely, this would introduce overhead in our application to remember which restaurants need to refresh at a specific time. I was thinking more so when the cache expires for a specific restaurant and when the endpoint responids with NOT FOUND, then we send request to refresh sku

**Comment by ld357** [comment]
Yup! We'll definitely need to refresh it if we hit NOT_FOUND but for your suggestion on when the cache expires, are you suggesting a somewhat "periodic" approach there?
