### ISSUE TITLE
Change Redis Connection to ENV (for Production)

### ISSUE THREAD

**Issue by ld357** [ubclaunchpad/foodies#80]
We currently need to modify the 'host' variable inside createClient for the Redis service if we want to rotate between a local Redis server, versus the Redis server on Docker. There should be another way to make this more convenient but requires more research!

**Comment by ericrkuo** [comment]
@ld357 I think this can be closed

**Comment by ld357** [comment]
Completed with [this PR](https://github.com/ubclaunchpad/foodies/pull/108)
